server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busdb
    username: root
    password: Manoj@510
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: manoj.balineni04@gmail.com
    password: ziac dsqc vzhn rawa

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true





